import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // default: [{ type: "autogenerated", dirName: "." }],
  docs: [
    "code-editor-setup",
    "project-setup",
    "workflow",
    "coding-standard",
    "best-practices",
    "readings",
    "state-management",
    "error-handling",
    "performance-optimization",
    "testing",
    {
      type: "category",
      label: "React Native",
      collapsible: true,
      items: ["react-native/environment-setup", "react-native/development"],
    },
    "additional-references",
  ],
};

export default sidebars;
